
import "../globals.css";
import { AuthProvider } from "./Providers";


export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><AuthProvider>{children}</AuthProvider></body>
    </html>
  );
}
