
import "../globals.css";


export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div lang="en">
      <div>{children}</div>
    </div>
  );
}
