
import "../globals.css";


export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
  icons:{
    icon:"/logo.png"
  }
};

export default function Layout({ children }) {
  return (
    <div lang="en">
      <div>{children}</div>
    </div>
  );
}
