import Navbar from "@/components/Navbar";
import "../globals.css";
import Footer from "@/components/Footer";
import Popup from "@/components/Popup";
import PopupVendorOffers from "@/components/PopupVendorOffers";

export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <main>
        <Navbar />
        {children}
        <Footer/>
        <Popup/>
        <PopupVendorOffers />
      </main>
    </html>
  );
}
