import { SideNavBar } from "@/components/backend/SideNavBar";
import "../../globals.css";
import { AuthProvider } from "../Providers";
import TopNavBar from "@/components/backend/TopNavBar";

export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="flex">
        <div className="w-1/5 ">
          <SideNavBar />
        </div>
        <div className="flex flex-col w-4/5">
          <div className="h-16">
            <TopNavBar />
          </div>

          <main className="min-h-screen">
            <AuthProvider>{children}</AuthProvider>
          </main>
        </div>
      </div>
    </html>
  );
}
