import { SideNavBar } from "@/components/backend/SideNavBar";
import "../../globals.css";
import TopNavBar from "@/components/backend/TopNavBar";

export const metadata = {
  title: "Shaadi Vyah",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div lang="en">
      <div className="lg:flex">
        <div className="w-1/5  ">
          <SideNavBar />
        </div>
        <div className="lg:flex flex-col lg:w-4/5">
          <div className="h-16 ">
            <TopNavBar />
          </div>
         
          <main className="min-h-screen ">
      {children}
          </main>
        </div>
      </div>
    </div>
  );
}
